spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/todolist
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop #create create-drop, update, validate, none
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        show_sql: true
  #    open-in-view: false
  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
